
import { AppStrings, LanguageCode, TargetLanguage } from './types';

export const TARGET_LANGUAGES: Record<TargetLanguage, { name: string, native: string }> = {
  fa: { name: 'Persian', native: 'فارسی' },
  en: { name: 'English', native: 'English' },
  es: { name: 'Spanish', native: 'Español' },
  ar: { name: 'Arabic', native: 'العربية' },
  fr: { name: 'French', native: 'Français' },
  de: { name: 'German', native: 'Deutsch' },
  tr: { name: 'Turkish', native: 'Türkçe' },
  ru: { name: 'Russian', native: 'Русский' }
};

export const LOCALES: Record<LanguageCode, AppStrings> = {
  fa: {
    title: 'سورن ترنسلیتور',
    uploadTitle: 'بارگذاری منبع SRT',
    uploadDesc: 'فایل زیرنویس را اینجا رها کنید یا برای انتخاب کلیک کنید',
    processBtn: 'شروع ترجمه هوشمند',
    downloadBtn: 'دریافت فایل ترجمه شده',
    creator: 'سورنا (TheSurenaX)',
    about: 'درباره پروژه',
    guide: 'راهنمای سیستم',
    tutorial: 'آموزش استخراج',
    processing: 'در حال تحلیل و ترجمه لایه‌های متنی...',
    finished: 'فرآیند ترجمه با موفقیت به پایان رسید.',
    error: 'خطای بحرانی در برقراری ارتباط با هوش مصنوعی.',
    contact: 'ارتباط با ما',
    home: 'پیشخوان',
    socials: 'شبکه‌های اجتماعی',
    telegramChannel: 'SurenaGR',
    telegramID: 'TheSurenaX',
    email: 'narutocoder.ir@gmail.com',
    aboutContent: 'سورن ترنسلیتور با هدف ارائه ترجمه‌های تراز اول سینمایی طراحی شده است. ما از مدل‌های پیشرفته برای درک مفاهیم دراماتیک استفاده می‌کنیم تا زیرنویسی فراتر از یک ترجمه ماشینی ساده خلق کنیم.',
    feature1Title: 'درک عصبی بافتار',
    feature1Desc: 'تحلیل زنجیره‌ای در بلوک‌های ۳۰ خطی برای حفظ انسجام دیالوگ‌ها.',
    feature2Title: 'پشتیبانی از ۸ زبان زنده',
    feature2Desc: 'امکان ترجمه زیرنویس به فارسی، انگلیسی، عربی، اسپانیایی و غیره.',
    guideStep1: 'فایل زیرنویس (.srt) خود را آپلود کنید.',
    guideStep2: 'زبان مقصد (Target Language) را از لیست انتخاب کنید.',
    guideStep3: 'روی دکمه شروع کلیک کنید تا پردازش آغاز شود.',
    guideStep4: 'فایل نهایی را دانلود کرده و لذت ببرید.',
    close: 'بستن',
    menu: 'ناوبری',
    heroSubtitle: 'تکنولوژی پیشرفته ترجمه خودکار زیرنویس با پشتیبانی از ۸ زبان زنده دنیا',
    statsUsers: 'کاربر ماهانه',
    statsTranslated: 'فایل پردازش شده',
    statsAccuracy: 'دقت زبان‌شناسی',
    faqTitle: 'سوالات متداول',
    faq1Q: 'آیا ترجمه دقیق است؟',
    faq1A: 'بله، مدل Gemini معنای واقعی اصطلاحات را درک کرده و ترجمه‌ای روان ارائه می‌دهد.',
    faq2Q: 'آیا فایل‌ها ذخیره می‌شوند؟',
    faq2A: 'خیر، تمامی پردازش‌ها در حافظه مرورگر و به صورت آنی انجام می‌شود.',
    faq3Q: 'محدودیت حجم فایل چقدر است؟',
    faq3A: 'فایل‌های بالای ۱ مگابایت به دلیل بهینه‌سازی سرعت پذیرفته نمی‌شوند.',
    whyAiTitle: 'چرا Soren Translator؟',
    whyAiDesc: 'ترکیب هنر ترجمه و قدرت محاسباتی هوش مصنوعی گوگل.',
    seoTextTitle: 'مرجع تخصصی ترجمه زیرنویس فیلم',
    seoTextBody: 'سورن ترنسلیتور بهترین ابزار برای ترجمه سریع زیرنویس به ۸ زبان مختلف با حفظ اصطلاحات و لحن سینمایی است.',
    tutorialTitle: 'آموزش استخراج زیرنویس',
    tutorialIntro: 'بسیاری از فیلم‌ها دارای زیرنویس داخلی هستند که برای ترجمه باید ابتدا آن‌ها را استخراج کنید.',
    tutorialStep1Title: 'استخراج با MKVToolNix',
    tutorialStep1Desc: 'نرم‌افزار را باز کرده و در بخش Tracks، تیک مربوط به Subtitles را برای استخراج بزنید.',
    tutorialStep2Title: 'تبدیل فرمت',
    tutorialStep2Desc: 'اگر زیرنویس شما فرمت SUB یا IDX است، آن را به SRT تبدیل کنید.',
    tutorialStep3Title: 'بارگذاری نهایی',
    tutorialStep3Desc: 'فایل SRT استخراج شده را در همین سایت آپلود و ترجمه کنید.',
    targetLangLabel: 'انتخاب زبان مقصد'
  },
  en: {
    title: 'Soren Translator',
    uploadTitle: 'Upload SRT Source',
    uploadDesc: 'Drag and drop your file here or click to browse',
    processBtn: 'Start AI Translation',
    downloadBtn: 'Download Translated File',
    creator: 'Surena (TheSurenaX)',
    about: 'About Project',
    guide: 'System Guide',
    tutorial: 'Extraction Tutorial',
    processing: 'Analyzing and translating text layers...',
    finished: 'Translation completed successfully.',
    error: 'Critical AI communication error.',
    contact: 'Contact Us',
    home: 'Console',
    socials: 'Social Media',
    telegramChannel: 'SurenaGR',
    telegramID: 'TheSurenaX',
    email: 'narutocoder.ir@gmail.com',
    aboutContent: 'Soren Translator is dedicated to high-end cinematic translations. We leverage cutting-edge models to understand dramatic nuances beyond simple machine logic.',
    feature1Title: 'Neural Contextual Sync',
    feature1Desc: 'Sequential analysis in 30-line blocks for maximum coherence.',
    feature2Title: '8-Language Support',
    feature2Desc: 'Translate to Persian, English, Arabic, Spanish, French, and more.',
    guideStep1: 'Upload your .srt source file.',
    guideStep2: 'Select your preferred Target Language.',
    guideStep3: 'Click the start button to initiate neural processing.',
    guideStep4: 'Download your translated file instantly.',
    close: 'Close',
    menu: 'Navigation',
    heroSubtitle: 'Advanced Neural Translation Interface Supporting 8 Global Languages',
    statsUsers: 'Monthly Active',
    statsTranslated: 'Assets Processed',
    statsAccuracy: 'Linguistic Precision',
    faqTitle: 'Frequently Asked Questions',
    faq1Q: 'Is the translation accurate?',
    faq1A: 'Yes, Gemini understands cinematic context and cultural idioms.',
    faq2Q: 'Are my files stored?',
    faq2A: 'No, all data is processed in-memory and deleted after download.',
    faq3Q: 'Is there a file size limit?',
    faq3A: 'Files over 1MB are restricted to maintain optimal performance.',
    whyAiTitle: 'Why Soren Translator?',
    whyAiDesc: 'Blending artistic translation with raw AI computational power.',
    seoTextTitle: 'Professional Subtitle Node',
    seoTextBody: 'Soren Translator is the premier tool for fast subtitle translation across 8 languages with cinematic accuracy.',
    tutorialTitle: 'Extracting Subtitles',
    tutorialIntro: 'Learn how to extract subtitle tracks from your media files.',
    tutorialStep1Title: 'MKVToolNix Method',
    tutorialStep1Desc: 'Open the tool, select your movie, and check the subtitle track for extraction.',
    tutorialStep2Title: 'Format Conversion',
    tutorialStep2Desc: 'Convert SUB/IDX formats to standard text-based SRT.',
    tutorialStep3Title: 'Import to Soren',
    tutorialStep3Desc: 'Upload the resulting SRT file here to get your translation.',
    targetLangLabel: 'Select Target Language'
  }
};

export const CREATOR_INFO = {
  name: 'Surena',
  telegram: 'TheSurenaX',
  channel: 'SurenaGR',
  email: 'narutocoder.ir@gmail.com'
};
